#! /bin/bash

mkdir -p debian/lightningbeam/usr/bin
mkdir -p debian/lightningbeam/usr/share/lightningbeam
mkdir -p debian/lightningbeam/usr/share/applications
mkdir -p debian/lightningbeam/usr/share/icons
mkdir -p debian/lightningbeam/DEBIAN

cp lightningbeam debian/lightningbeam/usr/bin/
cp lightningbeam.py debian/lightningbeam/usr/share/lightningbeam/
cp svlgui.py debian/lightningbeam/usr/share/lightningbeam/
cp misc_funcs.py debian/lightningbeam/usr/share/lightningbeam/
cp lightningbeam_windows.py debian/lightningbeam/usr/share/lightningbeam/
cp colors.py debian/lightningbeam/usr/share/lightningbeam/
cp gpl.txt debian/lightningbeam/usr/share/lightningbeam/
cp -r swfc debian/lightningbeam/usr/share/lightningbeam/
cp -r GUI debian/lightningbeam/usr/share/lightningbeam/
cp -r media debian/lightningbeam/usr/share/lightningbeam/

cp lightningbeam.desktop debian/lightningbeam/usr/share/applications/

cp media/icon_128.png debian/lightningbeam/usr/share/icons/lightningbeam.png

cp control debian/lightningbeam/DEBIAN/
cp postrm debian/lightningbeam/DEBIAN/
cp preinst debian/lightningbeam/DEBIAN/
cp postinst debian/lightningbeam/DEBIAN/
cp prerm debian/lightningbeam/DEBIAN/

echo 'media_path = "/usr/share/lightningbeam/"' > debian/lightningbeam/usr/share/lightningbeam/distpath.py
